### ISSUE TITLE
Create a master branch and use it as default

### ISSUE THREAD

**Issue by troyswanson** [gingerbreadassassin/RPiFanController#1]
It looks like you have `mongodb` set as the default branch (well, it's the only branch as of right now). Usually, projects has a `master` branch that represents the latest and greatest that people make Pull Requests into.

If the latest code is in the `mongodb` branch, you should create a new `master` branch from it and then push it to GitHub.

Most git projects have a master branch already, so you can either delete the current `master` branch and the create a new one from `mongodb`, or you can rebase the current master branch on top of `mongodb` and the pushing that to GitHub.

### Creating new `master`

```
git checkout mongodb
git branch -D master
git checkout -b master
git push
```

### Rebasing `master`

```
git checkout master
git rebase mongodb
git push
```

---

Once you've done that, you can set the default branch in the GitHub repo in the Settings page. Here's a [GitHub help article](https://help.github.com/articles/setting-the-default-branch/) on that subject.

**Comment by gingerbreadassassin** [comment]
Merged.
